# Run the equivalent of "apt-get update" 
- apt: update_cache=yes

- name: Install Xbmc dependencies
  apt: "pkg={{ item }} state=installed"
  with_items:
    - python-software-properties 
    - pkg-config
    - xinit 
    - x11-common 
    - x11-utils 
    - xorg 
    - libva-drm1 
#    - libva-intel-vaapi-driver 
#    - i965-va-driver 
    - vainfo 
    - lightdm 
    - lightdm-gtk-greeter 
    - udisks 
    - upower 
    - acpi 
    - acpi-support 
    - usbmount
 

- name: Xbmc | Add Xbmc repository
  apt_repository:
    repo: 'ppa:team-xbmc/ppa'
    state: present

- name: Install Xbmc 
  apt: "pkg=kodi state=installed"


